<a href="https://colab.research.google.com/github/Gioalf/AH2179/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [7]:
raw=pd.read_csv('/content/Dataset-PT.csv')

/tmp/ipython-input-1974507044.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  raw=pd.read_csv('/content/Dataset-PT.csv')

In [8]:
raw.head()

,Basic information,Unnamed: 1,Unnamed: 2,Unnamed: 3,Responsible variable,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Calendar_date,route_id,bus_id,stop_sequence,arrival_delay,dwell_time,travel_time_for_previous_section,scheduled_travel_time,upstream_stop_delay,origin_delay,...,factor(weather)Rain,factor(weather)Snow,factor(temperature)Cold,factor(temperature)Extra_cold,factor(temperature)Normal,factor(day_of_week)weekday,factor(day_of_week)weekend,factor(time_of_day)Afternoon_peak,factor(time_of_day)Morning_peak,factor(time_of_day)Off-peak
1,20220108,4,41344,1,151,0,0,120,100,100,...,0,0,0,0,1,0,1,0,0,1
2,20220108,4,41344,2,185,24,171,45,151,100,...,0,0,0,0,1,0,1,0,0,1
3,20220108,4,41344,3,186,0,55,41,185,100,...,0,0,0,0,1,0,1,0,0,1
4,20220108,4,41344,4,202,12,42,94,186,100,...,0,0,0,0,1,0,1,0,0,1

In [13]:
raw.iloc[0]

Basic information                                              Calendar_date
Unnamed: 1                                                          route_id
Unnamed: 2                                                            bus_id
Unnamed: 3                                                     stop_sequence
Responsible variable                                           arrival_delay
Unnamed: 5                                                        dwell_time
Unnamed: 6                                  travel_time_for_previous_section
Unnamed: 7                                             scheduled_travel_time
Unnamed: 8                                               upstream_stop_delay
Unnamed: 9                                                      origin_delay
Unnamed: 10                                               previous_bus_delay
Unnamed: 11                                        previous_trip_travel_time
Unnamed: 12                                                traffic_condition
Unnamed: 13                                                  recurrent_delay
Categorical varibles                                                 weather
Unnamed: 15                                                      temperature
Unnamed: 16                                                      day_of_week
Unnamed: 17                                                      time_of_day
Categorical variables (dummy variables)            factor(weather)Light_Rain
Unnamed: 19                                        factor(weather)Light_Snow
Unnamed: 20                                            factor(weather)Normal
Unnamed: 21                                              factor(weather)Rain
Unnamed: 22                                              factor(weather)Snow
Unnamed: 23                                          factor(temperature)Cold
Unnamed: 24                                    factor(temperature)Extra_cold
Unnamed: 25                                        factor(temperature)Normal
Unnamed: 26                                       factor(day_of_week)weekday
Unnamed: 27                                       factor(day_of_week)weekend
Unnamed: 28                                factor(time_of_day)Afternoon_peak
Unnamed: 29                                  factor(time_of_day)Morning_peak
Unnamed: 30                                      factor(time_of_day)Off-peak
Name: 0, dtype: object